gtk3: fix clang builds
Fixes Clang build failure on Darwin caused by missing sincos().

Darwin’s libSystem does not provide the GNU extension sincos(), which causes
gtk3’s test helper (gtkgears.c) to fail to build with Clang:

    ../tests/gtkgears.c:309:5: error: call to undeclared library function 'sincos' with type 'void (double, double *, double *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        sincos (angle, &s, &c);
        ^
    note: include the header <math.h> or explicitly provide a declaration for 'sincos'

Backports https://gitlab.gnome.org/GNOME/gtk/-/commit/6cb612ac15923844155885b7eaa02764de84936e and extends
it to the test programs. Additionally avoids using sincos() when compiling with
Clang, since HAVE_SINCOS may be incorrectly set on Darwin.

Can be dropped once upstream Meson correctly detects absence of sincos() on Darwin.