thunderbird: enable darwin builds
Leaving `betterbird` marked as broken for MacOS due to a compilation
error in `style` dependency:

> error[E0412]: cannot find type `_Pred` in this scope